### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by GermanBluefox** [ha4us/base#1]
Hallo Ulf,
Dein Projekt sieht sehr interessant aus.
Was ist das? Kann man irgendwo darüber lesen?

Frage ich mal direkt. Hast du Interesse zusammenarbeiten?
Gruß,
Bluefox

**Comment by ulfalfa** [comment]
Hi Bluefox,
Dokumentation gibt es noch gar keine - ich habe das tatsächlich eher für mich als Lernfeld für angular und nodejs  angefangen.
Impuls war, als ihr damals wieder mit den files in ioBroker angefangen habt - ich fand die Idee mit Datenbank und Eventbus sehr spannend und deswegen habe ich dann Mqtt und MongoDb angefangen. Von den Ideen ist eine Menge ccu.io und ioBroker Minded :-)

Gruß,
Ulf
